import Head from "next/head";
import {
  Banner,
  FlashDeals,
  NewArrivals,
  OurServices,
  RandomProducts,
  TopCategories,
  DiscountBanner,
  AllCatagories,
} from "../components/mainComponents/Home";
import { BottomBar, Footer, Navbar } from "../components/sharedComponents";

export default function Home() {
  return (
    <div>
      <Head>
        <title>E Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Navbar />
        <Banner />
        <FlashDeals />
        <TopCategories />
        <NewArrivals />
        <DiscountBanner />
        <AllCatagories />
        <RandomProducts />
        <OurServices />
        <Footer />
        <BottomBar />
      </div>
    </div>
  );
}
